# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0004_auto_20170311_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('resource', models.TextField(max_length=5000)),
                ('attendance', models.PositiveIntegerField()),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_activity', to='details.ClassDetail')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='details.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('other_details', models.TextField(max_length=5000)),
            ],
        ),
    ]
