# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20170311_1409'),
        ('activity', '0002_auto_20170311_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad'), ('Please Stop', 'Please Stop')], default='Please Stop', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.FeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Student'),
        ),
    ]
