# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20170311_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanswer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_answer', to='activity.Activity'),
        ),
        migrations.AlterField(
            model_name='feedbackquestion',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_question', to='activity.ActivityType'),
        ),
    ]
