# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20170313_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackanswer',
            name='activity',
        ),
    ]
