# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_remove_feedbackquestion_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackanswer',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_ans', to='activity.Activity'),
            preserve_default=False,
        ),
    ]
