# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20170421_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanswer',
            name='answer',
            field=models.CharField(choices=[('Excelent', 'Excelent'), ('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], default='Please Stop', max_length=50),
        ),
    ]
