# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20170313_2114'),
        ('activity', '0009_auto_20170422_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='attendance',
        ),
        migrations.AddField(
            model_name='activity',
            name='attendance',
            field=models.ManyToManyField(to='details.Student'),
        ),
    ]
