# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20170422_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanswer',
            name='answer',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Please Stop', max_length=50),
        ),
    ]
