# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20170311_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdetail',
            old_name='join_year',
            new_name='year',
        ),
    ]
