# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20170311_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hod', models.CharField(max_length=125)),
                ('no_of_teachers', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='classdetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='details.Branch'),
        ),
    ]
