# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20170311_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['usn']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['emp_id']},
        ),
        migrations.RenameField(
            model_name='classdetail',
            old_name='no_of_stu',
            new_name='no_of_student',
        ),
    ]
