# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20170313_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetail',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_detail', to='details.Branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='details.ClassDetail'),
        ),
    ]
